# SPDX-License-Identifier: GPL-2.0-only
obj-y				+= clk.o
obj-$(CONFIG_LOONGSON1_LS1B)	+= clk-loongson1b.o
obj-$(CONFIG_LOONGSON1_LS1C)	+= clk-loongson1c.o
obj-$(CONFIG_LOONGSON_2K1000)	+= clk-loongson2k1000.o
obj-$(CONFIG_LOONGSON_2K500)	+= clk-loongson2k500.o